### ISSUE TITLE
nhpup on mobile is at bottom

### ISSUE THREAD

**Issue by alexbonjour** [alexbonjour/rules-of-thumb#1]
On mobile, nhpup should appear below the item, not at the bottom of the page.

**Comment by Wieschie** [comment]
I'm not sure about this one.  I used [this script](https://github.com/nhoening/popup.js) for the popups.

**Comment by alexbonjour** [comment]
I did some looking at it and it looks like it puts the pup div at the bottom of the page when on mobile.   That makes it look like this on mobile:

Siyalatas/argaiv: 
<input-box>
Gold (?):
<input-box>
etc.
etc.
Formulas
<bunch of formulas here>
<pup>popup box, formatted same as desktop shown here</pup>

What I want is no changes on desktop, something like this on mobile:
Siyalatas/argaiv: 
<input-box>
Gold (?):
<input-box>
<pup-for-gold>stuff about gold ancients</pup-for-gold>
etc.
etc.
Formulas
<bunch of formulas here>
