### ISSUE TITLE
1.0 - Transcendence update

### ISSUE THREAD

**Issue by genewitch** [alexbonjour/rules-of-thumb#17]
There's no more Iris, and it looks like a couple of other ancients changed as well (i.e. got way more expensive.)

I know that working on a beta premise is silly, but at least you can get a head start!

**Comment by alexbonjour** [comment]
Thanks for the note.   I've started looking at the save files and how to create the new version of clicker lister.   I'm curious to see how many formulas are in the new rules of thumb.

**Comment by Wieschie** [comment]
The [1.0 beta](http://www.clickerheroes.com/test519/) is up, and saves will be importable into the live version.

Right now there isn't a new rules of thumb available.  The main heroes affect by the new Outsiders are Siya/Lib and Solomon, although the active ancients make take on greater importance now that the rewards are much higher for deep runs.

I can post on this again when there's more information available - feel free to let me know if you want any help.

**Comment by Wieschie** [comment]
Here's a preliminary analysis: https://www.reddit.com/r/ClickerHeroes/comments/4naohc/math_and_transcendance/

I may start working on a pull request if I don't get a response, so just let me know if you start on anything!

**Comment by alexbonjour** [comment]
Thanks for the info.   I'm not sure yet how to implement the "old" levels in the new math like  "oldDogcog" and "oldAtman" levels. 

Does the inclusion of those values make a calculator based solely on Siyalatas impossible now?   Any thoughts?

**Comment by alexbonjour** [comment]
I wonder if we can use this: https://www.reddit.com/r/ClickerHeroes/comments/4naohc/math_and_transcendance/d42r5jt to figure out what value to use.

**Comment by Wieschie** [comment]
I haven't take the time to sit down and completely follow Sugima's math, but I did pull out this:

> To simplify the equations, i suggest to consider (1+e-0.02·Bubos ) and (2-e-0.034·Chronos ) as constants, using the old ancient values (this is false, but it's the easiest thing that comes to my mind) .
It's likely more work can be done to come up with a better or simpler formula there.  Right now Dora is the only value drastically affected by the inclusion of the old value in the calculation - one option is to leave that out entirely for the time being until we have a consensus.

**Comment by alexbonjour** [comment]
Thanks for the praise.    Maybe we move forward with leaving out those parts of the equation.   Lemme create a feature branch so we can both see efforts and not muck up the gh-pages branch.

**Comment by alexbonjour** [comment]
transcendence is the new branch.   https://github.com/alexbonjour/rules-of-thumb/tree/transcendence  If I do anything, it'll be synced there.   If you make a pull request, do it against that branch and we can work to something good.      I don't mind if you send over small pull requests.

**Comment by Wieschie** [comment]
Okay, thanks for the info. I was mostly offering to work on it in the case
that you were inactive. I'm glad to see you still maintaining things!

I'll avoid stepping on your toes for now but may contribute a few small
things later on if I can.

**Comment by alexbonjour** [comment]
I opened a few issues for the items that could be improved.   Main calculator definitely supports 1.0 now.
