### ISSUE TITLE
locale for TP and thousands is inconsistent

### ISSUE THREAD

**Issue by alexbonjour** [alexbonjour/rules-of-thumb#22]
Use locale for number formatting so in US we get:

123,456
and TP 1.2

and in Germany we get:
123.456
and TP 1,2

**Comment by Wieschie** [comment]
We might actually be able to drop numeral.js and use a built-in function for this.  I haven't figured out an easy way to test it but I think it's what you want.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by alexbonjour** [comment]
The other option given by the bug finder is to always use english style.   That apparently matches the game play:  https://www.reddit.com/r/ClickerHeroes/comments/4ny5su/updated_simple_rules_of_thumb_calculator_for_10/d48jjar 

Not sure which to pursue.   Be deliberately wrong for non-US people to match the game or be correct. :)

**Comment by alexbonjour** [comment]
Ended up changing input type=number to type=text.

type=number has the locale issues and you can't force it's locale.  Instead I've got type=text and keypress function defined in jquery to limit text entry to "1234567890." .
