### ISSUE TITLE
incremental cost for leveling up ancient

### ISSUE THREAD

**Issue by terryys** [alexbonjour/rules-of-thumb#31]
It would be nice if the calculator can show the number of hero souls required when we enter a new value for Siyalatas, Argaiv.

**Comment by alexbonjour** [comment]
How would you input the start and end values?

If the field says "1000"   and you press "+1000" 4 times, how would you know what start value it was using?   

If you paused and hit +100, would it calculate the cost of the last 100 levels or the last 4100 levels?

**Comment by terryys** [comment]
How about adding another input field representing the "present Siyalatas, Argaiv levels", and calculate the souls required based on this present level and intended level?
Another idea is to calculate the optimal levels based on the current level and souls available, assuming currently the ancient levels are distributed according to the formulae.
But all these will require additional input field(s) and the calculator would not be that simple anymore.
