### ISSUE TITLE
Solomon Stagnation

### ISSUE THREAD

**Issue by ShiroiKa** [alexbonjour/rules-of-thumb#32]
Once you reach the cap on transcendent power, it becomes far less effective to level Solomon at all. Atman still works fine, but the benefit of improving Solomon only allows you to reach your TP cap a few levels faster. There's a point very, very far down the road where Solomon could make the base hero soul value of a primal boss become relevant again, but that's long after Transcending again is strongly recommended.
It might be a good idea to include some reference between the Solomon level growth stopping entirely and the Borg/number of hero souls needed to be sacrificed to get the number of Ancient Souls you currently have. You know, so the calculator stops telling you to pour trillions of Hero Souls into a vastly inferior Ancient after you've reached that point of the run. It would mean that it was slightly more viable to push a little deeper by focusing on your gold/damage ancients and maybe swing another Ancient Soul or two on a given Transcendence run in the same time.
Also, are you sure it doesn't eventually become more effective to add a few more levels to Chor'gorloth and Xyliqil? I haven't seen the math very clearly and I had to wonder if at very high levels it might not do best to dump another 20 and 10 in them to double their effects, but I can see how Phandorys and Ponyboy might not have a point where they stop being more useful because of the math involved. I just wanted to make sure that it didn't _eventually_ decay to the point that the 30 extra souls needed to double both of those bonuses became a better purchase.
Anyways, this calculator has really helped me out a lot and for only finding two minor little nitpicks to even consider, I'm very impressed with the overall design. Thank you a lot for making this!

**Comment by alexbonjour** [comment]
Thanks for the feedback.  For Solomon I've seen references stating that it's still valuable to keep upping Solomon so you reach the cap earlier.  

For the outsiders, I've been just using the rules of thumb that were published earlier.    I'm thinking about adding the spreadsheet values to this calculator too.
