### ISSUE TITLE
Outsiders [AS]

### ISSUE THREAD

**Issue by oxo1978** [alexbonjour/rules-of-thumb#37]
Hello,
I have a problem with Outsiders tab. I don't know why, but since 3-4 days in outsiders swection ther is only one collumn - Spreadsheet. Rules of the Thumb has gone. It was very helpful for me. Is there any chance to return it? Thanks in advance.
![capture1](https://cloud.githubusercontent.com/assets/28555070/25836789/02ae71ae-348a-11e7-8aab-d9a1c68ce122.jpg)

**Comment by alexbonjour** [comment]
The rules of thumb results were based on math that has since been proven not to be optimal.
