### ISSUE TITLE
format outputs so you can read millions easier

### ISSUE THREAD

**Issue by alexbonjour** [alexbonjour/rules-of-thumb#8]
show 17,013,231 instead of 17013231

**Comment by Wieschie** [comment]
I submitted a pull request to implement this.

**Comment by alexbonjour** [comment]
Sweet, I'll look at that tonight.   I see you switched them from number to text which is what I was thinking too.

**Comment by alexbonjour** [comment]
Merged and fixed.   Gracias @Wieschie
